version: "3.9"
services:
  app:
    build: .
    container_name: revizserver
    command: gunicorn --timeout 240 --workers 1 --bind 0.0.0.0:8000 FaceRecognitionServer.wsgi
    volumes:
      - .:/RevizServer
    ports:
      - 5555:5555
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: revizserver_db
    command: postgres -c 'max_connections=1000'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=revizserver
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  nginx:
    build: ./nginx
    container_name: revizserver_nginx
    depends_on:
      - app
    volumes:
      - ./static/:/var/www/static/
      - ./media/:/var/www/media/
    ports:
      - "80:80"
      - "443:443"
