# Generated by Django 4.1.7 on 2023-03-11 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cord_type', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('separable', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'cords',
            },
        ),
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('Spotrebič', 'Spotrebič'), ('Predlžovačka', 'Predlžovačka')], max_length=127)),
                ('device_name', models.CharField(max_length=255)),
                ('device_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10)),
                ('device_operability', models.CharField(choices=[('držané v ruke', 'držané v ruke'), ('prenosné', 'prenosné'), ('pripevnené, neprenosné', 'pripevnené, neprenosné')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'device templates',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_location', models.CharField(max_length=50)),
                ('facility_building', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'voltages',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_SN', models.CharField(max_length=255)),
                ('power', models.DecimalField(decimal_places=4, max_digits=16)),
                ('current', models.DecimalField(decimal_places=4, max_digits=16)),
                ('qr_text', models.CharField(max_length=255)),
                ('cord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.cord')),
                ('device_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.devicetemplate')),
                ('device_voltage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.voltage')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.facility')),
            ],
            options={
                'verbose_name_plural': 'devices',
            },
        ),
    ]
