# Generated by Django 4.1 on 2022-08-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'devices'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.facility'),
        ),
    ]
