# Generated by Django 4.1 on 2022-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_facility_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_text_id',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
