# Generated by Django 4.1 on 2022-08-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_device_qr_text_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='deviceName',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='qr_text_id',
            new_name='qrText',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='location',
            new_name='facilityLocation',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='facilityName',
        ),
        migrations.RemoveField(
            model_name='device',
            name='qr_image',
        ),
    ]
